export interface imagesObject {
  [key: string]: string
}

const images: imagesObject = {
  // General
  arrowRightBlue: require('./Images/General/arrowRightBlue.png'),
  arrowBack: require('./Images/General/arrowBack.png'),
  arrowLeftActive: require('./Images/General/arrowLeftActive.png'),
  arrowLeftInactive: require('./Images/General/arrowLeftInactive.png'),
  arrowRightActive: require('./Images/General/arrowRightActive.png'),
  arrowRightInactive: require('./Images/General/arrowRightInactive.png'),
  calendar: require('./Images/General/calendar.png'),
  clock: require('./Images/General/clock.png'),
  close: require('./Images/General/close.png'),
  customize: require('./Images/General/customize.png'),
  done: require('./Images/General/done.png'),
  doneSmall: require('./Images/General/done_small.png'),
  dropdownArrows: require('./Images/General/dropdownArrows.png'),
  info: require('./Images/General/info.png'),
  logo: require('./Images/General/logo.png'),
  plus: require('./Images/General/plus.png'),
  remove: require('./Images/General/remove.png'),
  search: require('./Images/General/search.png'),
  sortAsc: require('./Images/General/sortAsc.png'),
  sortDesc: require('./Images/General/sortDesc.png'),
  warning: require('./Images/General/warning.png'),
  // Sidebar
  addCompanyLogo: require('./Images/Sidebar/addCompanyLogo.png'),
  analytics: require('./Images/Sidebar/analytics.png'),
  analyticsActive: require('./Images/Sidebar/analyticsActive.png'),
  equipment: require('./Images/Sidebar/equipment.png'),
  equipmentActive: require('./Images/Sidebar/equipmentActive.png'),
  map: require('./Images/Sidebar/map.png'),
  mapActive: require('./Images/Sidebar/mapActive.png'),
  settings: require('./Images/Sidebar/settings.png'),
  settingsActive: require('./Images/Sidebar/settingsActive.png'),
  sidebarLogo: require('./Images/Sidebar/sidebarLogo.png'),
  // Account
  email: require('./Images/Account/email.png'),
  hidden: require('./Images/Account/hidden.png'),
  checkmark: require('./Images/Account/check.png'),
  password: require('./Images/Account/password.png'),
  user: require('./Images/Account/user.png'),
  userSettings: require('./Images/Account/userSettings.png'),
  siteListSettings: require('./Images/Account/siteListSettings.png'),
  xmark: require('./Images/Account/clear.png'),
  visible: require('./Images/Account/visible.png'),
  // Map
  accentGear: require('./Images/Map/accentGear.png'),
  accessWorking: require('./Images/Map/accessWorking.png'),
  hoeWorking: require('./Images/Map/backhoeWorking.png'),
  compactorWorking: require('./Images/Map/compactorWorking.png'),
  dumperWorking: require('./Images/Map/dumperWorking.png'),
  cloudy: require('./Images/Map/cloudy.png'),
  dozerIdle: require('./Images/Map/dozerIdle.png'),
  dozerWorking: require('./Images/Map/dozerWorking.png'),
  excavatorWorking: require('./Images/Map/excavatorWorking.png'),
  mapGroup: require('./Images/Map/mapGroup.png'),
  mapGroup1: require('./Images/Map/mapGroup1.png'),
  mapGroup2: require('./Images/Map/mapGroup2.png'),
  mapGroup3: require('./Images/Map/mapGroup3.png'),
  mapGroup4: require('./Images/Map/mapGroup4.png'),
  mapGroup5: require('./Images/Map/mapGroup5.png'),
  mapPoint: require('./Images/Map/mapPoint.png'),
  rollerWorking: require('./Images/Map/rollerWorking.png'),
  telehandlerWorking: require('./Images/Map/telehandlerWorking.png'),
  truckWorking: require('./Images/Map/truckWorking.png'),
  siteList: require('./Images/Map/siteList.png'),
  // Equipment
  access: require('./Images/Equipment/access.png'),
  assign: require('./Images/Equipment/assign.png'),
  hoe: require('./Images/Equipment/backhoe.png'),
  compactor: require('./Images/Equipment/compaction.png'),
  dozer: require('./Images/Equipment/dozer.png'),
  dumper: require('./Images/Equipment/dumper.png'),
  excavator: require('./Images/Equipment/excavator.png'),
  gear: require('./Images/Equipment/gear.png'),
  issue: require('./Images/Equipment/issue.png'),
  lender: require('./Images/Equipment/lender.png'),
  location: require('./Images/Equipment/location.png'),
  roller: require('./Images/Equipment/roller.png'),
  telehandler: require('./Images/Equipment/telehandler.png'),
  truck: require('./Images/Equipment/truck.png'),
  // Analytics
  // Dashboard
  arrowTrendUp: require('./Images/Dashboard/arrowTrendUp.png'),
  co2: require('./Images/Dashboard/co2.png'),
  gas: require('./Images/Dashboard/gas.png'),
  // Reports
  assetSummary: require('./Images/Reports/assetSummary.png'),
  telematics: require('./Images/Reports/telematicsReport.png'),
  // STATIC TEST ASSETS -- REMOVE AS THEY BECOME UNNECESSARY
  catHero: require('./Images/catHero.png'),
}

export default images
